version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3 bucket
          command: aws s3 sync . s3://learncicd --exclude '.circleci/*'
            --exclude '.git/*'
workflows:
  version: 2
  workflow:
    jobs:
      - build
